site_name: Flexcyon Theme Docs
site_url: https://flexcyon.github.io/docs-en
site_description: >-
  Documentation for the Flexcyon Theme.

repo_url: https://github.com/bladeacer/flexcyon
repo_name: bladeacer/flexcyon
copyright: Copyright &copy; <a href="https://github.com/bladeacer" target="_blank" rel="noopener noreferrer">bladeacer</a> 2025

plugins:
  - search:
      lang:
        - en
        - zh
  - tags
  - meta
  - i18n:
      reconfigure_material: true
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          default: true
          name: 简体中文
          link: /zh/
          build: true
          site_name: Flexcyon 主题文档
          nav_translations:
            Foreword: 前言
            README: 自述
            About: 关于主题
            Copyright: 版权
            Screenshots: 截图 
            Installation: 下载
            Extensions: 附加插件或 CSS
            Design Principles: 设计原则
            License: 许可证
            Roadmap: 路线图
            Credits: 鸣谢
            Contributors: 贡献者
            Styling: 样式
            Style Settings: 样式设置
            Tools and Software: 工具与软件
  - git-revision-date-localized:
      enable_creation_date: true
extra_css:
  - ./stylesheets/styles.css
theme:
  name: material
  language: en
  custom_dir: docs/overrides
  include_search_page: false
  search_index_only: true
  icon:
    repo: material/github
    logo: material/file-document

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  font:
    text: Roboto Slab
    code: Roboto Mono

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  markdown_extensions:
    - attr_list
    - toc:
        permalink: true
    - footnotes

  extra:
    tags:
      Style Settings: style_settings
      README: readme
      Logs: logs
      Plugins: plugins
      Snippets: snippets
      Styling: styling
      Callouts: callouts

nav:
  - Foreword: "index.md"
  - README: 
    - About: "README/index.md"
    - Screenshots: "README/page-1.md"
    - Installation: "README/page-2.md"
    - Extensions: "README/page-3.md"
    - Design Principles: "README/page-4.md"
    - License: "README/license.md"
    - Roadmap: "README/roadmap.md"
  - Credits:
    - Contributors: "credits/index.md"
    - Tools and Software: "credits/page-1.md"
  - Styling:
    - Styling: "Styling/index.md"
    - Style Settings:
      - Style Settings: "Styling/Style-Settings/index.md"
      - Modes: "Styling/Style-Settings/Modes/index.md"
      - Editor: 
        - Editor: "Styling/Style-Settings/Editor/index.md"
        - Accent Colors: "Styling/Style-Settings/Editor/Accent-Colors/index.md"
        - Base Colors: "Styling/Style-Settings/Editor/Base-Colors/index.md"
        - Typography: "Styling/Style-Settings/Editor/Typography/index.md"
        - Headings: "Styling/Style-Settings/Editor/Headings/index.md"
        - Inline Title: "Styling/Style-Settings/Editor/Inline-Title/index.md"
        - Code Blocks: "Styling/Style-Settings/Editor/Code-Blocks/index.md"
        - UI Font Size: "Styling/Style-Settings/Editor/UI-Font-Size/index.md"
        - Table: "Styling/Style-Settings/Editor/Table/index.md"
        - Files: "Styling/Style-Settings/Editor/Files/index.md"
        - Workspace:
          - Workspace: "Styling/Style-Settings/Editor/Workspace/index.md"
          - Prompts: "Styling/Style-Settings/Editor/Workspace/prompts/index.md"
        - Animations: "Styling/Style-Settings/Editor/Animations/index.md"
        - Editor Background: "Styling/Style-Settings/Editor/Editor-Background/index.md"
        - Layout: "Styling/Style-Settings/Editor/Layout/index.md"
        - Callouts: "Styling/Style-Settings/Editor/Callouts/index.md"
        - Horizontal Rule: "Styling/Style-Settings/Editor/Horizontal-Rule/index.md"
        - Checkboxes: "Styling/Style-Settings/Editor/Checkboxes/index.md"
        - Bullet Lists: "Styling/Style-Settings/Editor/Bullet-Lists/index.md"
        - Numbered Lists: "Styling/Style-Settings/Editor/Numbered-Lists/index.md"
        - Media: "Styling/Style-Settings/Editor/Media/index.md"
        - Links: "Styling/Style-Settings/Editor/Links/index.md"
        - Properties: "Styling/Style-Settings/Editor/Properties/index.md"
        - Status Bar: "Styling/Style-Settings/Editor/Status-Bar/index.md"
        - Title Bar: "Styling/Style-Settings/Editor/Title-Bar/index.md"
        - Line Numbers: "Styling/Style-Settings/Editor/Line-Numbers/index.md"
        - Cursor: "Styling/Style-Settings/Editor/Cursor/index.md"
        - Graph: "Styling/Style-Settings/Editor/Graph/index.md"
        - View Header: "Styling/Style-Settings/Editor/View-Header/index.md"
        - Icons: "Styling/Style-Settings/Editor/Icons/index.md"
