site_name: Flexcyon Theme Docs
site_url: https://flexcyon.github.io/docs-en
site_description: >-
  Documentation for the Flexcyon Theme.

repo_url: https://github.com/bladeacer/flexcyon
repo_name: bladeacer/flexcyon
copyright: Copyright &copy; bladeacer 2025

plugins:
  - search:
      lang:
        - en
        - zh
  - tags
  - meta
  - i18n:
      reconfigure_material: true
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          default: true
          name: 简体中文
          link: /docs-en/zh/
          build: true
          site_name: Flexcyon 主题文档
          nav_translations:
            Foreword: 前言
  - git-revision-date-localized:
      enable_creation_date: true
extra_css:
  - docs/stylesheets/styles.css
theme:
  name: material
  language: en
  custom_dir: docs/overrides
  include_search_page: false
  search_index_only: true
  icon:
    repo: material/github
    logo: material/file-document

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  font:
    text: Source Sans Pro
    code: Source Code Pro

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  markdown_extensions:
    - attr_list
    - toc:
        permalink: true
    - footnotes

  extra:
    tags:
      Style Settings: style_settings
      README: readme
      Logs: logs
      Plugins: plugins
      Snippets: snippets
      Styling: styling
      Callouts: callouts

nav:
  - Foreword: "index.md"
