site_name: Flexcyon Theme Docs
site_url: https://flexcyon.github.io/docs-en
site_description: >-
  Documentation for the Flexcyon Theme.

repo_url: https://github.com/bladeacer/flexcyon
repo_name: bladeacer/flexcyon
copyright: Copyright &copy; <a href="https://github.com/bladeacer" target="_blank" rel="noopener noreferrer">bladeacer</a> 2025

plugins:
  - search:
      lang:
        - en
        - zh
  - tags
  - meta
  - i18n:
      reconfigure_material: true
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          default: true
          name: 简体中文
          link: /zh/
          build: true
          site_name: Flexcyon 主题文档
          nav_translations:
            Foreword: 前言
            README: 自述
            About: 关于主题
            Copyright: 版权
            Screenshots: 截图 
            Installation: 下载
            Extensions: 附加插件或 CSS
            Design Principles: 设计原则
            License: 许可证
            Roadmap: 路线图
            Credits: 鸣谢
            Contributors: 贡献者
  - git-revision-date-localized:
      enable_creation_date: true
extra_css:
  - ./stylesheets/styles.css
theme:
  name: material
  language: en
  custom_dir: docs/overrides
  include_search_page: false
  search_index_only: true
  icon:
    repo: material/github
    logo: material/file-document

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  font:
    text: Roboto Slab
    code: Roboto Mono

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  markdown_extensions:
    - attr_list
    - toc:
        permalink: true
    - footnotes

  extra:
    tags:
      Style Settings: style_settings
      README: readme
      Logs: logs
      Plugins: plugins
      Snippets: snippets
      Styling: styling
      Callouts: callouts

nav:
  - Foreword: "index.md"
  - README: 
    - About: "README/index.md"
    - Screenshots: "README/page-1.md"
    - Installation: "README/page-2.md"
    - Extensions: "README/page-3.md"
    - Design Principles: "README/page-4.md"
    - License: "README/license.md"
    - Roadmap: "README/roadmap.md"
  - Credits:
    - Contributors: "credits/index.md"
