site_name: Flexcyon Theme Docs
site_url: https://flexcyon-docs.readthedocs.io/zh-cn/latest/
repo_url: https://github.com/bladeacer/flexcyon
repo_name: bladeacer/flexcyon
copyright: >
  Copyright &copy; bladeacer 2025
plugins:
  - search
  - tags
  - meta
  - git-revision-date-localized:
      enable_creation_date: true
extra_css:
  - stylesheets/styles.css
theme:
  name: material
  custom_dir: ./docs/overrides
  icon:
    repo: material/github
    logo: material/file-document

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  font:
    text: Source Sans Pro
    code: Source Code Pro
  features:
    - navigation.instant.preview
    - navigation.path
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - content.action.view
    - content.code.copy
  markdown_extensions:
    - attr_list
    - toc:
        permalink: true
    - footnotes

  extra:
    tags:
      Style Settings: style_settings
      README: readme
      Logs: logs
      Plugins: plugins
      Snippets: snippets
      Styling: styling
      Callouts: callouts