baseURL = 'https://flexcyon.github.io/docs-en/'
locale = 'en-gb'
title = 'Flexcyon Documentation'
defaultContentLanguage = "en"
ignoreLogs = ['warning-goldmark-raw-html']

[module.imports]
path = "github.com/imfing/hextra"


[languages.en]
label = "English"
contentDir = "content/en"
locale = "en-gb"


[languages.zh]
title = "Flexcyon 中文文档"
label = "简体中文"
contentDir = "content/zh"
locale = "zh-cn"


[params]
defaultContentLanguageInSubdir = true
customCSS = ["css/custom.css"]

[params.navbar]
displayLanguageSwitch = true

[params.search]
  type = "flexsearch"
  [params.search.flexsearch]
    js = "js/vendor/flexsearch.bundle.min.js"

[[menu.main]]
name = "Search"
weight = 1

[menu.main.params]
type = "search"


[[menu.main]]
name = "Theme Toggle"
weight = 2

[menu.main.params]
type = "theme-toggle"
label = true


[[menu.main]]
name = "Language Switcher"
weight = 3

[menu.main.params]
type = "language-switch"
label = true


[[menu.main]]
name = "GitHub"
weight = 4
url = "https://github.com/bladeacer/flexcyon"

[menu.main.params]
icon = "github"

[markup.highlight]
noClasses = true
