baseURL = 'https://flexcyon.github.io/docs-en/'
locale = 'en-gb'
title = 'Flexcyon Documentation'
defaultContentLanguage = "en"

[module.imports]
path = "github.com/imfing/hextra"

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1

  [languages.zh]
    languageName = "简体中文"
    contentDir = "content/zh"
    weight = 2

# Documentation Link
[[menu.main]]
  name = "Documentation"
  pageRef = "/docs"
  weight = 1

# Blog Link
[[menu.main]]
  name = "Blog"
  pageRef = "/blog"
  weight = 2

# About Link
[[menu.main]]
  name = "About"
  pageRef = "/about"
  weight = 3

# Search Bar (Hextra specific)
[[menu.main]]
  name = "Search"
  weight = 4
  [menu.main.params]
    type = "search"

# External GitHub Link
[[menu.main]]
  name = "GitHub"
  weight = 5
  url = "https://github.com/imfing/hextra"
  [menu.main.params]
    icon = "github"
