name: Deploy zh branch

on: push

jobs:
  copy:
    name: Copy my folder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout and prepare branch
        shell: bash
        env:
          SRC_FOLDER_PATH: 'translation-zh'
          TARGET_BRANCH: 'zh-cn'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f)
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch
          git checkout $TARGET_BRANCH
          git checkout ${GITHUB_REF##*/} -- $files
          mv $SRC_FOLDER_PATH docs
          mv $SRC_FOLDER_PATH/README.md ./README.md

      - name: Get GitHub App installation token
        id: app-token
        uses: actions/create-github-app-token@v2.0.6
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          installation-id: ${{ secrets.GH_APP_INSTALLATION_ID }}

      - name: Commit and push changes
        shell: bash
        env:
          TARGET_BRANCH: 'zh-cn'
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git add -A
          git diff-index --quiet HEAD || git commit -am "Deploy translated files"
          git push https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git $TARGET_BRANCH