name: Move Files to Translated Branch

on:
  push:
    branches:
      - master

jobs:
  move_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Checkout target branch (or create if needed)
        run: |
          git fetch origin zh-cn || true
          git checkout zh-cn || git checkout --orphan zh-cn
          git reset --hard origin/zh-cn || git reset --hard

      - name: Create target directory (if it doesn't exist)
        run: mkdir -p docs

      - name: Move files to target branch directory
        run: |
          source_directory="translation"
          target_directory="docs"
          if [ -d "$source_directory" ]; then
            mv "$source_directory"/* "$target_directory"/
          else
            echo "Source directory '$source_directory' not found."
          fi

      - name: Set up PAT for pushing
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

      - name: Add and commit changes
        run: |
          git add docs/*
          git commit -m "Move translated files" || echo "No changes to commit"

      - name: Push changes
        run: git push origin zh-cn